services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: preh-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped
    networks:
      - preh-network
  preh-wldt-system:
    build:
      context: ./preh-wldt-system
    container_name: emergency-wldt-subsystem
    environment:
      - MQTT_BROKER_URL=tcp://mosquitto:1883
    depends_on:
      - mosquitto
    restart: unless-stopped
    networks:
      - emergency-network

networks:
  emergency-network:
    driver: bridge