package it.ausl.emergency;

import it.ausl.emergency.adapter.physical.AmbulancePhysicalAdapter;
import it.ausl.emergency.payload.AmbulanceTelemetryPayload;
import it.ausl.emergency.shadowing.AmbulanceShadowingFunction;
import it.ausl.emergency.twin.AmbulanceDigitalTwin;
import it.ausl.emergency.utils.AmbulanceKeywords;
import it.wldt.core.engine.DigitalTwinEngine;
import it.wldt.core.state.DigitalTwinState;
import it.wldt.core.state.DigitalTwinStateProperty;
import it.wldt.exception.WldtEngineException;
import org.junit.jupiter.api.*;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

/**
 * JUnit 5 Test Suite for AmbulanceDigitalTwin.
 * Simulates a realistic emergency mission timeline and structural transitions 
 * generated by AnyLogic agents, verifying transactional properties and vehicle domain events.
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class AmbulanceDigitalTwinTest {

    private static final String VEHICLE_ID = "AMB-11";
    private static final long PROPAGATION_MS = 2_000L;
    private static final long BOOT_WAIT_MS = 3_000L;

    private DigitalTwinEngine engine;
    private AmbulanceDigitalTwin ambulanceTwin;
    private AmbulancePhysicalAdapter physicalAdapter;

    @BeforeEach
    public void setUp() throws Exception {
        AmbulanceShadowingFunction shadowingFunction = 
                new AmbulanceShadowingFunction("ambulance-shadowing-" + VEHICLE_ID);

        // Custom twin internally initializes physical and digital adapters with default shared configurations
        ambulanceTwin = new AmbulanceDigitalTwin("dt-ambulance-" + VEHICLE_ID, shadowingFunction);
        physicalAdapter = ambulanceTwin.getPhysicalAdapter();

        engine = new DigitalTwinEngine();
        engine.addDigitalTwin(ambulanceTwin);
        engine.startAll();

        System.out.println("\n[TEST-SETUP] AmbulanceDigitalTwin Engine started. Waiting for warm-up sync...\n");
        Thread.sleep(BOOT_WAIT_MS);
    }

    @AfterEach
    public void tearDown() {
        if (engine != null) {
            try {
                engine.stopAll();
            } catch (WldtEngineException e) {
                e.printStackTrace();
            }
            System.out.println("\n[TEST-TEARDOWN] AmbulanceDigitalTwin Engine halted.\n");
        }
    }

    @Test
    @Order(1)
    @DisplayName("Full Operational Mission Timeline -> Properties synchronization and edge alerts validation")
    public void testAmbulanceMissionLifecycleAndEvents() throws Exception {

        // ── PHASE 1: At Rest at Stationary Point ─────────────────────────────────
        log("PHASE 1: Vehicle Standby at Station Base");
        injectVehicleTelemetry(new AmbulanceTelemetryPayload(
                AmbulanceKeywords.STATE_AT_REST, 44.32414, 12.05190, "null", "null", "stationaryPoint3", 1.0, 0, false, false, 767.19, 0.0
        ));

        Thread.sleep(PROPAGATION_MS);
        assertPropertyEquals(AmbulanceKeywords.STATE_PROPERTY_KEY, AmbulanceKeywords.STATE_AT_REST);
        assertPropertyEquals(AmbulanceKeywords.FUEL_LEVEL_PROPERTY_KEY, 1.0);
        assertPropertyEquals(AmbulanceKeywords.PATIENT_ID_PROPERTY_KEY, "null");

        // ── PHASE 2: Dispatch - Moving to Patient ────────────────────────────────
        log("PHASE 2: Dispatcher Command — Moving to Patient Position");
        injectVehicleTelemetry(new AmbulanceTelemetryPayload(
                AmbulanceKeywords.STATE_MOVING_TO_PATIENT, 44.32414, 12.05190, "P-767193", "null", "stationaryPoint3", 1.0, 0, false, false, 767.19, 10428.1
        ));

        Thread.sleep(PROPAGATION_MS);
        assertPropertyEquals(AmbulanceKeywords.STATE_PROPERTY_KEY, AmbulanceKeywords.STATE_MOVING_TO_PATIENT);
        assertPropertyEquals(AmbulanceKeywords.PATIENT_ID_PROPERTY_KEY, "P-767193");
        assertPropertyEquals(AmbulanceKeywords.TRIP_DISTANCE_PROPERTY_KEY, 10428.1);

        // ── PHASE 3: Arrival - Taking Patient On Board ───────────────────────────
        log("PHASE 3: Arrived on Target Location — Taking Patient");
        injectVehicleTelemetry(new AmbulanceTelemetryPayload(
                AmbulanceKeywords.STATE_TAKING_PATIENT, 44.23095, 12.06534, "P-767193", "hospitalForli", "stationaryPoint3", 0.95, 0, false, false, 1289.3, 10428.1
        ));

        Thread.sleep(PROPAGATION_MS);
        assertPropertyEquals(AmbulanceKeywords.STATE_PROPERTY_KEY, AmbulanceKeywords.STATE_TAKING_PATIENT);
        assertPropertyEquals(AmbulanceKeywords.HOSPITAL_ID_PROPERTY_KEY, "hospitalForli");
        assertPropertyEquals(AmbulanceKeywords.FUEL_LEVEL_PROPERTY_KEY, 0.95);

        // ── PHASE 4: Transit to Hospital & Critical Fuel Event Trigger ──────────
        log("PHASE 4: Emergency Transit — Clinical Deterioration Response with Low Fuel");
        injectVehicleTelemetry(new AmbulanceTelemetryPayload(
                AmbulanceKeywords.STATE_MOVING_TO_HOSPITAL, 44.20596, 12.01896, "P-767193", "hospitalCesena", "stationaryPoint3", 0.12, 0, true, false, 2489.3, 29324.0
        ));

        Thread.sleep(PROPAGATION_MS);
        assertPropertyEquals(AmbulanceKeywords.STATE_PROPERTY_KEY, AmbulanceKeywords.STATE_MOVING_TO_HOSPITAL);
        assertPropertyEquals(AmbulanceKeywords.HOSPITAL_ID_PROPERTY_KEY, "hospitalCesena");
        assertPropertyEquals(AmbulanceKeywords.FUEL_LEVEL_PROPERTY_KEY, 0.12);
        assertPropertyEquals(AmbulanceKeywords.NEEDS_REFUELING_PROPERTY_KEY, true);

        // ── PHASE 5: Destination Reached - Hospital Handover ────────────────────
        log("PHASE 5: Hospital Emergency Hub Reached — Handover Mode Active");
        injectVehicleTelemetry(new AmbulanceTelemetryPayload(
                AmbulanceKeywords.STATE_HANDOVER, 44.13484, 12.25984, "P-767193", "hospitalCesena", "stationaryPoint3", 0.10, 0, true, false, 3459.2, 29324.0
        ));

        Thread.sleep(PROPAGATION_MS);
        assertPropertyEquals(AmbulanceKeywords.STATE_PROPERTY_KEY, AmbulanceKeywords.STATE_HANDOVER);

        // ── PHASE 6: Post-Mission Resource Management - Sanitizing & Maintenance ─
        log("PHASE 6: Patient Hemorrhage Cleanup — Sanitizing and Maintenance Flags");
        injectVehicleTelemetry(new AmbulanceTelemetryPayload(
                AmbulanceKeywords.STATE_SANITIZING, 44.13484, 12.25984, "P-767193", "hospitalCesena", "stationaryPoint3", 0.10, 1, true, true, 4479.2, 29324.0
        ));

        Thread.sleep(PROPAGATION_MS);
        assertPropertyEquals(AmbulanceKeywords.STATE_PROPERTY_KEY, AmbulanceKeywords.STATE_SANITIZING);
        assertPropertyEquals(AmbulanceKeywords.MISSIONS_PROPERTY_KEY, 1);
        assertPropertyEquals(AmbulanceKeywords.NEEDS_MAINTENANCE_PROPERTY_KEY, true);

        System.out.println("\n[TEST] === Ambulance Digital Twin lifecycle properties successfully verified. ===\n");
    }

    // ── Telemetry Ingestion Simulator Helper ─────────────────────────────────

    private void injectVehicleTelemetry(AmbulanceTelemetryPayload payload) {
        try {
            String simulatedJson = "{"
                    + "\"state\":\"" + payload.state() + "\","
                    + "\"lat\":" + payload.lat() + ","
                    + "\"lon\":" + payload.lon() + ","
                    + "\"patientId\":\"" + payload.patientId() + "\","
                    + "\"hospitalId\":\"" + payload.hospitalId() + "\","
                    + "\"homeBaseId\":\"" + payload.homeBaseId() + "\","
                    + "\"fuelLevel\":" + payload.fuelLevel() + ","
                    + "\"missionsSinceMaintenance\":" + payload.missionsSinceMaintenance() + ","
                    + "\"needsRefueling\":" + payload.needsRefueling() + ","
                    + "\"needsMaintenance\":" + payload.needsMaintenance() + ","
                    + "\"timestamp\":" + payload.timestamp() + ","
                    + "\"tripDistanceSinceEmergency\":" + payload.tripDistanceSinceEmergency()
                    + "}";

            System.out.println("[ANYLOGIC-AMB-SIM] topic  : ces/ambulance/" + VEHICLE_ID + "/state");
            System.out.println("[ANYLOGIC-AMB-SIM] payload: " + simulatedJson + "\n");

            physicalAdapter.onAmbulanceTelemetryReceived(payload);

        } catch (Exception e) {
            fail("Telemetry simulation injection pipeline crashed: " + e.getMessage());
        }
    }

    // ── State Assertion Utility ──────────────────────────────────────────────

    private <T> void assertPropertyEquals(String propertyKey, T expectedValue) throws Exception {
        DigitalTwinState state = ambulanceTwin
                .getShadowingFunction()
                .getDigitalTwinStateManager()
                .getDigitalTwinState();

        assertNotNull(state, "The running DigitalTwinState core reference object cannot be null.");

        Optional<DigitalTwinStateProperty<?>> optProp = state.getProperty(propertyKey);
        assertTrue(optProp.isPresent(), "Property matching key '" + propertyKey + "' was not found in DT State.");

        Object actualValue = optProp.get().getValue();
        assertEquals(expectedValue, actualValue, "Validation Failure for ambulance state metric: '" + propertyKey + "'");

        System.out.println("[ASSERT ✓] Property verified: " + propertyKey + " = " + actualValue);
    }

    private static void log(String phase) {
        System.out.println("\n[TEST] == " + phase.toUpperCase() + " ==========================\n");
    }
}